name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: leedg92/java-springboot
          stage: main
          yaml: |
            name: board
            app: java@17
            options:
              ports: 8080
              env:
                - name: DATABASE_HOST
                  value: mariadb
                - name: DATABASE_PORT
                  value: "3306"
                - name: DATABASE_USERNAME
                  value: leedg92
                - name: DATABASE_PASSWORD
                  value: dlehd123
                - name: DATABASE_NAME
                  value: boardDB
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: java-springboot
